# Generated by Django 4.1.5 on 2023-01-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="MyUsers",
            new_name="MyUser",
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
        migrations.AddField(
            model_name="course",
            name="user_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.myuser"
            ),
        ),
    ]
