# Generated by Django 4.1.5 on 2023-01-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_course_rename_myusers_myuser_delete_courses_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="user_id",
            new_name="user_ref",
        ),
    ]
